### ISSUE TITLE
FP issue - Washtrading

### ISSUE THREAD

**Issue by Ivan1905** [frwd-1/Wash-Trade-Detector#2]
Hey,

I have observed a few FPs coming from the wash-trading detection bot. It seems that the bot is flagging addresses which are receiving NFTs coming from the address that fund the main account. However, there isn't a sale here but rather a transfer of ownership. So, although who is giving and receiving the NFT is the same person, it is just a transfer of ownership and not a wash trading event.

Example 1
https://explorer.forta.network/alert/0xbc93923881a0c73bbccae7cb544b6db62748e3ecfddbb29a6c67e2740d774c6f
https://polygonscan.com/address/0x948d4dfaa42978e2b86143f916b91cce3a45312a

Example 2
https://explorer.forta.network/alert/0x4cf19d9ea2e342bea63fd713b10c8166d2e3db237606fbba4b0951eccfec52ab
https://polygonscan.com/address/0x5c9739b6e1ffb164a55fbd00447500af7c46c4db

Example 3
https://explorer.forta.network/alert/0xb50f66f28b093b7e374ff5a730c68b5d20ee789ee0c2d0db1ee639eb0cac06df
https://polygonscan.com/address/0x97a13c6dd7367fdeaa7a76fddb3c755008cc5d25

**Comment by frwd-1** [comment]
resolved offline
